name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint HTML/CSS/JS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependências de lint
        run: |
          npm init -y
          npm install htmlhint stylelint stylelint-config-standard --save-dev

      - name: Rodar lint no HTML
        run: npx htmlhint "**/*.html" --ignore "coverage/**"

      - name: Rodar lint no CSS
        run: npx stylelint "**/*.css" --ignore "coverage/**"

  discord:
    name: Discord Commits
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true